### PR TITLE
feat(addListener): throw an error if next, error or complete functions are missing

### PR DESCRIPTION
**Pull request by Widdershin**
This class of error is a compiler error in TypeScript, but is a runtime error in JS. Currently we get an error like "this._n is not a function" which is quite cryptic to an end user.

I would add a test for this, but since it's a compiler error in TS I can't see any way to do so.

### CODE REVIEW

**Comment by staltz** [comment]
> I would add a test for this, but since it's a compiler error in TS I can't see any way to do so.

Here's a dirty trick I sometimes use:

```typescript
var listener = <Listener<T>> <any> incompleteListener;
```

:dancers:

**Comment by erkarl** [comment]
Does this mean that the end-user won't be able to subscribe to a stream without providing ***all*** 3 functions (onNext, onError, onCompleted)?

**Comment by Widdershin** [comment]
That is correct, and is in fact by design. See #1.

**Comment by erkarl** [comment]
@Widdershin thanks for clearing it up.

**Comment by Widdershin** [comment]
@staltz fixed the failures (which were the result of done.fail being undefined) and added some tests for these errors. I feel like this should be good to merge 😺

**Comment by erkarl** [comment]
👍

**Comment by staltz** [comment]
Merged as of https://github.com/staltz/xstream/commit/10721b692f5474a88883bddad3f4f9242f05cd43, thanks @Widdershin. I ended up trimming down the code, for size.

**Pull request closed without merging**
