### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SteveALee**
@staltz - updating to be inline with your recent comment on gitter.

### CODE REVIEW

**Comment by staltz** [comment]
Hi @SteveALee  :)
Thanks for submitting this PR, we appreciate any kind of desire to help. Before merging this PR I need you to notice the first line in the README.md. It has instructions about how to "edit" it.

**Comment by SteveALee** [comment]
@staltz  I'm sorry. Can you send me a link because all I see in Master README is the ASCII logo at the start of the file.

I thought it strange I could not find the latest page in the usual gh-pages branch.

**Comment by staltz** [comment]
Check the raw md file, not the "preview"

**Comment by SteveALee** [comment]
doh - you mean the "really raw" file! :)

**Comment by SteveALee** [comment]
I did, will look again.

Steve Lee

**Pull request closed without merging**
