### PR TITLE
fix(README): typo

### PR DESCRIPTION
**Pull request by AdamWendell**

### CODE REVIEW

**Comment by staltz** [comment]
Uh, sorry, did you see the first 3 lines of the README?

**Comment by AdamWendell** [comment]
Oh, no I was reading on Github when I saw it. Sorry, will fix it when I get home!

**Comment by AdamWendell** [comment]
So now the edit is in the right place. Sorry for the inconvenience.

**Comment by staltz** [comment]
Thanks @AdamWendell

**Pull request merged**
