### PR TITLE
improve TypeScript typings for delay, dropRepeats, dropUnti, split

### PR DESCRIPTION
**Pull request by whitecolor**
A little bit breaking because `delay` doesn't not allow to specify type, so one will have to fix it in the codebase.

### CODE REVIEW

**Comment by staltz** [comment]
Thanks @whitecolor (even though I took a long time to merge it)

**Comment by whitecolor** [comment]
@staltz some conflicts there were?

**Comment by staltz** [comment]
Should have released it as major (breaking change).

**Comment by whitecolor** [comment]
Ah ok, I was on vacation anyway, so I didn't miss much 😄

**Pull request merged**
