### PR TITLE
Add a note about extra methods in the README

### PR DESCRIPTION
**Pull request by nornagon**
I had no idea these existed and there's all sorts of neat stuff in there!

### CODE REVIEW

**Comment by staltz** [comment]
There is already a link, have you seen it? https://github.com/staltz/xstream#extra-operators-and-factories

**Comment by nornagon** [comment]
Oh, I completely missed that! I thought I searched through the README to see if there was a link, but my Cmd+F must have failed.

I think it would be worth moving the link to a more prominent place (alongside all the other API methods), as it's easy to miss where it currently is. I only realized those operators existed after someone linked me to those docs on Gitter.

I can update the PR to remove the other link to remove the redundancy if you like. If you still disagree that it's easy to miss or don't believe it's important to surface, go ahead and close the PR :)

**Comment by jvanbruegge** [comment]
As I had the same problem initially, I would suggest to merge this.

**Comment by staltz** [comment]
Alright, @nornagon could you update the PR to remove the existing mention of extras, include your new mention new the table of contents, and fix `XStream` to `xstream`?

**Comment by nornagon** [comment]
Not sure which table of contents you're referring to?

**Comment by staltz** [comment]
Thanks @nornagon

**Pull request merged**
