### PR TITLE
Reject method

### PR DESCRIPTION
**Pull request by joaomilho**
I got a little tired of doing...  `.filter(R.complement(R.isNil))`.

I'm not really sure on the implementation 'though. If you wanna keep it, LMK if it's ok.

### CODE REVIEW

**Comment by staltz** [comment]
Hi @joaomilho, thanks for the work you put into this PR. On the other hand, we probably don't take anymore new simple operators, due to the design goals in contributing.md: https://github.com/staltz/xstream/blob/master/CONTRIBUTING.md

**Comment by joaomilho** [comment]
Fine, how do you suggest this should be done then? extra/other lib?

**Comment by staltz** [comment]
`R.complement` or `filter(x => x != null)`. Consider how the addition of `reject` would make it quicker to *write* code, but slower to *read and understand* for other developers, because they need to read up about yet another operator.

**Comment by joaomilho** [comment]
Fair enough.

**Pull request closed without merging**
