### PR TITLE
Use export default xs to enable autoimport in VSCode

### PR DESCRIPTION
**Pull request by Nitive**
vscode-xs-import-demo

### CODE REVIEW

**Comment by staltz** [comment]
Nice! Thanks

**Comment by staltz** [comment]
Very good point @ryota-ka 
I hadn't intended `xs<T>` to be a valid use of xstream, but since enough people used that, it's a breaking change for them.

**Comment by staltz** [comment]
That said, it's perceivable only for TypeScript users who directly use it. Those who indirectly use it (like in onionify `lib/pickMerge.d.ts`) can reinstall/recompile and no error would happen.

**Comment by ryota-ka** [comment]
@staltz Then any plans to release a new version of `cycle-onionify` with recompiled `lib/*.d.ts`?
A project relying on it reports errors as below and doesn't compile.

```
node_modules/cycle-onionify/lib/pickCombine.d.ts(3,64): error TS2304: Cannot find name 'xs'.
node_modules/cycle-onionify/lib/pickCombine.d.ts(3,95): error TS2304: Cannot find name 'xs'.
node_modules/cycle-onionify/lib/pickMerge.d.ts(3,62): error TS2304: Cannot find name 'xs'.
node_modules/cycle-onionify/lib/pickMerge.d.ts(3,93): error TS2304: Cannot find name 'xs'.
```

**Comment by staltz** [comment]
Thanks! I released onionify v5.1.0 can you test it?

**Comment by ryota-ka** [comment]
@staltz Thank you for your quick response and action.
I tested the new version and everything seems perfect now 🎉

**Comment by staltz** [comment]
@Nitive That's a wise idea. Let's do that, the PR would be welcomed.

**Pull request merged**
