### PR TITLE
feat(buffer): buffer operator that splits input stream into arrays by …

### PR DESCRIPTION
**Pull request by VKobeliatsky**
…separator stream

buffer operator accepts a separator stream as an argument. It accumulates input stream events into
arrays and emits them when separator stream emits or closes. Output stream is closed when separator stream is closed. #goodnessSquad

### CODE REVIEW

**Comment by VKobeliatsky** [comment]
With @mightyiam during #goodnessSquad

**Comment by staltz** [comment]
Thanks @VKobeliatsky. This relates to #142 and seems mostly good to merge. I'll do some refactoring after merging, to make the code style consistent with the rest. And also semantically I need to change the test `it('should complete when separator is completed after the source'` because the output stream **should** complete if the **source** completes. It just makes more sense (no reason to keep something open if you know no more values will come) and also RxJS does like this.

**Comment by VKobeliatsky** [comment]
Hi @staltz, thanks for the merge!
The only thing that I am worried about is your suggestion on *complete* behavior. I imagined `separator` stream as a control mechanism over when the `out` stream gets data. So when `separator` completes `out` will never get data and is good to complete, too. If we complete when `input` stream completes we will have to either flush aggregated items immediately and complete (which will break the concept that `separator` is control), or just complete and potentially lose some items.

**Comment by staltz** [comment]
> If we complete when input stream completes we will have to either flush aggregated items immediately and complete (which will break the concept that separator is control)

This is the change that I did. I think it's sensible because these semantics have been used in RxJS for years and people haven't complained about it as far as I know.

**Comment by VKobeliatsky** [comment]
Convinced then, thanks!

Also, looks like I forgot to edit `tsconfig.json`

**Comment by staltz** [comment]
I'll do that, no worries.

**Comment by mightyiam** [comment]
Awesome, @VKobeliatsky!

**Pull request merged**
